services:
  not-found:
    build: .
    environment:
      PORT: 8000
      TYPE: text/html
      CONTENT: >
        <html>
          <head>
            <title>404 Not Found</title>
          </head>
          <body>
            <h1>404 Not Found</h1>
            <p>The requested URL was not found on this server.</p>
          </body>
        </html>
      SERVER_NAME: "Not Found"
      STATUS_CODE: 404
    ports:
      - "8000:8000"